# Generated by Django 3.0.7 on 2020-06-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testing_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct', models.IntegerField()),
                ('CD', models.IntegerField()),
                ('age', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('early_vote', models.CharField(max_length=8)),
                ('party', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='testing_data_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('CD', models.IntegerField()),
                ('age', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('early_vote', models.CharField(max_length=8)),
                ('party', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='testing_data_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('CD', models.IntegerField()),
                ('age', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('early_vote', models.CharField(max_length=8)),
                ('early_vote_score', models.IntegerField()),
                ('accuracy_result', models.CharField(max_length=1)),
                ('party', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='training_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct', models.IntegerField()),
                ('CD', models.IntegerField()),
                ('age', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('early_vote', models.CharField(max_length=8)),
                ('party', models.CharField(max_length=3)),
            ],
        ),
    ]
