# Generated by Django 3.0.7 on 2020-06-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200623_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing_data_result',
            name='early_vote_score',
            field=models.CharField(max_length=8),
        ),
    ]
