# Generated by Django 3.0.7 on 2020-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testing_data_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing_data_input',
            name='early_vote',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='training_data_raw',
            name='early_vote',
            field=models.CharField(max_length=8),
        ),
    ]
