# Generated by Django 3.0.7 on 2020-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200622_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing_data_input',
            name='early_vote',
            field=models.CharField(max_length=8),
        ),
    ]
